### ISSUE TITLE
ChatGPT needs to be added

### ISSUE THREAD

**Issue by Mike-0000** [robchahin/sso-wall-of-shame#440] opened 2024-01-11 22:27 UTC
**What is the vendor's name?**
OpenAI/ChatGPT

**What is the vendor's pricing site?**
https://openai.com/chatgpt/pricing

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$25/user/month

**What is the minimum pricing for SSO support?**
Unknown, 150 user minimum required for SSO

**Does this pricing info come from a quote or other non-public source?**

**Are there any caveats we should list in the footnotes?**
SSO locked off to Enterprise customers, 150 user minimum

**Comment by techdarko** [comment] 2024-01-12 20:29
Duplicate of #439 - closing to consolidate.

**Closed by techdarko** 2024-01-12 20:29 UTC
